package messages

import "fmt"
import "github.com/shopspring/decimal"

type PortRange struct {
	_struct   bool `codec:",uint"` //encode struct with "unsigned integer" keys
	LowerPort *int `json:"lower-port" codec:"8,omitempty"`
	UpperPort *int `json:"upper-port" codec:"9,omitempty"`
}

type SourceICMPTypeRange struct {
	_struct   bool `codec:",uint"` //encode struct with "unsigned integer" keys
	LowerType *int `json:"lower-type" codec:"32771,omitempty"`
	UpperType *int `json:"upper-type" codec:"32772,omitempty"`
}

type ACL struct {
	_struct        bool   `codec:",uint"` //encode struct with "unsigned integer" keys
	AclName        string `json:"ietf-dots-signal-control:acl-name" codec:"23,omitempty"`
	ActivationType *int   `json:"ietf-dots-signal-control:activation-type" codec:"49,omitempty"`
}

type MitigationScope struct {
	_struct bool    `codec:",uint"` //encode struct with "unsigned integer" keys
	Scopes  []Scope `json:"scope"             codec:"2"`
	// only used in response
	ClientDomainIdentifier string `json:"cdid" codec:"3,omitempty"`
}

type Scope struct {
	_struct bool `codec:",uint"` //encode struct with "unsigned integer" keys
	// A unique identifier that is randomly generated by a DOTS client to prevent request collisions. (used only server side in BODY)
	ClientIdentifier string `json:"cuid" codec:"4,omitempty"`
	// Identifier for the mitigation request
	MitigationId *int `json:"mid" codec:"5,omitempty"`
	// prefix
	TargetPrefix []string `json:"target-prefix" codec:"6,omitempty"`
	// lower-port upper-port
	TargetPortRange []PortRange `json:"target-port-range" codec:"7,omitempty"`
	// Internet Protocol number
	TargetProtocol []int `json:"target-protocol" codec:"10,omitempty"`
	// FQDN
	FQDN []string `json:"target-fqdn" codec:"11,omitempty"`
	// URI
	URI []string `json:"target-uri" codec:"12,omitempty"`
	// alias name
	AliasName []string `json:"alias-name" codec:"13,omitempty"`
	// source prefix
	SourcePrefix []string `json:"ietf-dots-call-home:source-prefix" codec:"32768,omitempty"`
	// source port range
	SourcePortRange []PortRange `json:"ietf-dots-call-home:source-port-range" codec:"32769,omitempty"`
	// source icmp type range
	SourceICMPTypeRange []SourceICMPTypeRange `json:"ietf-dots-call-home:source-icmp-type-range" codec:"32770,omitempty"`
	// list of acl
	AclList []ACL `json:"ietf-dots-signal-control:acl-list" codec:"22,omitempty"`
	// lifetime
	Lifetime *int `json:"lifetime" codec:"14,omitempty"`
	// attack-status
	AttackStatus *int `json:"attack-status" codec:"29,omitempty"`
	// If false, mitigation is triggered only if the signal channel is lost. This is an optional attribute.
	TriggerMitigation *bool `json:"trigger-mitigation" codec:"45,omitempty"`
}

type MitigationRequest struct {
	_struct         bool            `codec:",uint"` //encode struct with "unsigned integer" keys
	MitigationScope MitigationScope `json:"ietf-dots-signal-channel:mitigation-scope" codec:"1"`
}

/*
 * get last client-identifier
 */
func (m *MitigationRequest) EffectiveClientIdentifier() string {
	return m.MitigationScope.Scopes[0].ClientIdentifier
}

/*
 * get last client-domain-identifier
 */
func (m *MitigationRequest) EffectiveClientDomainIdentifier() string {
	return m.MitigationScope.ClientDomainIdentifier
}

/*
 * get last client-domain-identifier
 */
func (m *MitigationRequest) EffectiveMitigationId() *int {
	return m.MitigationScope.Scopes[0].MitigationId
}

/*
 * set client-identifier
 */
func (m *MitigationRequest) UpdateClientIdentifier(cuid string) {
	m.MitigationScope.Scopes[0].ClientIdentifier = cuid
}

/*
 * set client-domain-identifier
 */
func (m *MitigationRequest) UpdateClientDomainIdentifier(cdid string) {
	m.MitigationScope.ClientDomainIdentifier = cdid
}

/*
 * set mitigation-id
 */
func (m *MitigationRequest) UpdateMitigationId(mid *int) {
	m.MitigationScope.Scopes[0].MitigationId = mid
}

/*
 * Convert MitigationRequests to strings
 */
func (m *MitigationRequest) String() (result string) {
	result = "\n \"ietf-dots-signal-channel:mitigation-scope\":\n"
	for key, scope := range m.MitigationScope.Scopes {
		result += fmt.Sprintf("   \"%s[%d]\":\n", "scope", key+1)
		if scope.MitigationId != nil {
			result += fmt.Sprintf("     \"%s\": %d\n", "mid", *scope.MitigationId)
		}
		if scope.TargetPrefix != nil {
			for k, v := range scope.TargetPrefix {
				result += fmt.Sprintf("     \"%s[%d]\": %s\n", "target-prefix", k+1, v)
			}
		}
		if scope.TargetPortRange != nil {
			for k, v := range scope.TargetPortRange {
				result += fmt.Sprintf("     \"%s[%d]\":\n", "target-port-range", k+1)
				if v.LowerPort != nil {
					result += fmt.Sprintf("       \"%s\": %d\n", "lower-port", *v.LowerPort)
				}
				if v.UpperPort != nil {
					result += fmt.Sprintf("       \"%s\": %d\n", "upper-port", *v.UpperPort)
				}
			}
		}
		if scope.TargetProtocol != nil {
			for k, v := range scope.TargetProtocol {
				result += fmt.Sprintf("     \"%s[%d]\": %d\n", "target-protocol", k+1, v)
			}
		}
		if scope.FQDN != nil {
			for k, v := range scope.FQDN {
				result += fmt.Sprintf("     \"%s[%d]\": %s\n", "target-fqdn", k+1, v)
			}
		}
		if scope.URI != nil {
			for k, v := range scope.URI {
				result += fmt.Sprintf("     \"%s[%d]\": %s\n", "target-uri", k+1, v)
			}
		}
		if scope.AliasName != nil {
			for k, v := range scope.AliasName {
				result += fmt.Sprintf("     \"%s[%d]\": %s\n", "alias-name", k+1, v)
			}
		}
		if scope.SourcePrefix != nil {
			for k, v := range scope.SourcePrefix {
				result += fmt.Sprintf("     \"%s[%d]\": %s\n", "ietf-dots-call-home:source-prefix", k+1, v)
			}
		}
		if scope.SourcePortRange != nil {
			for k, v := range scope.SourcePortRange {
				result += fmt.Sprintf("     \"%s[%d]\":\n", "ietf-dots-call-home:source-port-range", k+1)
				if v.LowerPort != nil {
					result += fmt.Sprintf("       \"%s\": %d\n", "lower-port", *v.LowerPort)
				}
				if v.UpperPort != nil {
					result += fmt.Sprintf("       \"%s\": %d\n", "upper-port", *v.UpperPort)
				}
			}
		}
		if scope.SourceICMPTypeRange != nil {
			for k, v := range scope.SourceICMPTypeRange {
				result += fmt.Sprintf("     \"%s[%d]\":\n", "ietf-dots-call-home:source-icmp-type-range", k+1)
				if v.LowerType != nil {
					result += fmt.Sprintf("       \"%s\": %d\n", "lower-type", *v.LowerType)
				}
				if v.UpperType != nil {
					result += fmt.Sprintf("       \"%s\": %d\n", "upper-type", *v.UpperType)
				}
			}
		}
		if scope.AclList != nil {
			for k, v := range scope.AclList {
				result += fmt.Sprintf("     \"%s[%d]\":\n", "ietf-dots-signal-control:acl-list", k+1)
				result += fmt.Sprintf("       \"%s\": %s\n", "ietf-dots-signal-control:acl-name", v.AclName)
				if v.ActivationType != nil {
					result += fmt.Sprintf("       \"%s\": %d\n", "ietf-dots-signal-control:activation-type", *v.ActivationType)
				}
			}
		}
		if scope.Lifetime != nil {
			result += fmt.Sprintf("     \"%s\": %d\n", "lifetime", *scope.Lifetime)
		}
		if scope.AttackStatus != nil {
			result += fmt.Sprintf("     \"%s\": %d\n", "attack-status", *scope.AttackStatus)
		}
		if scope.TriggerMitigation != nil {
			result += fmt.Sprintf("     \"%s\": %t\n", "trigger-mitigation", *scope.TriggerMitigation)
		}
	}
	return
}

type SignalConfigRequest struct {
	_struct       bool          `codec:",uint"` //encode struct with "unsigned integer" keys
	SignalConfigs SignalConfigs `json:"ietf-dots-signal-channel:signal-config" codec:"30"`
}

type SignalConfigs struct {
	_struct          bool         `codec:",uint"` //encode struct with "unsigned integer" keys
	MitigatingConfig SignalConfig `json:"mitigating-config" codec:"32"`
	IdleConfig       SignalConfig `json:"idle-config"       codec:"44"`
}

type IntCurrent struct {
	_struct      bool `codec:",uint"` //encode struct with "unsigned integer" keys
	CurrentValue *int `json:"current-value" codec:"36,omitempty"`
}

type DecimalCurrent struct {
	_struct      bool             `codec:",uint"` //encode struct with "unsigned integer" keys
	CurrentValue *decimal.Decimal `json:"current-value-decimal" codec:"43,omitempty"`
}

type SignalConfig struct {
	_struct bool `codec:",uint"` //encode struct with "unsigned integer" keys
	// Identifier for the DOTS signal channel session configuration data represented as an integer.
	// This identifier MUST be generated by the DOTS client.  This document does not make any assumption about how this
	// identifier is generated. This is a mandatory attribute.
	SessionId int `json:"sid" codec:"31,omitempty"`
	// Heartbeat interval to check the DOTS peer health.  This is an optional attribute.
	HeartbeatInterval IntCurrent `json:"heartbeat-interval" codec:"33,omitempty"`
	// Maximum number of missing heartbeat response allowed. This is an optional attribute.
	MissingHbAllowed IntCurrent `json:"missing-hb-allowed" codec:"37,omitempty"`
	// Maximum number of retransmissions for a message (referred to as MAX_RETRANSMIT parameter in CoAP).
	// This is an optional attribute.
	MaxRetransmit IntCurrent `json:"max-retransmit" codec:"38,omitempty"`
	// Timeout value in seconds used to calculate the initial retransmission timeout value (referred to as ACK_TIMEOUT
	// parameter in CoAP). This is an optional attribute.
	AckTimeout DecimalCurrent `json:"ack-timeout" codec:"39,omitempty"`
	// Random factor used to influence the timing of retransmissions (referred to as ACK_RANDOM_FACTOR parameter in
	// CoAP).  This is an optional attribute.
	AckRandomFactor DecimalCurrent `json:"ack-random-factor" codec:"40,omitempty"`
}

type SignalChannelRequest struct {
	_struct bool `codec:",uint"` //encode struct with "unsigned integer" keys
}

/*
 * Convert SignalConfigRequest to strings
 */
func (m *SignalConfigRequest) String() (result string) {
	var current_float float64
	result = "\n \"ietf-dots-signal-channel:signal-config\":\n"
	result += fmt.Sprintf("   \"%s\":\n", "mitigating-config")
	result += fmt.Sprintf("     \"%s\":\n", "heartbeat-interval")
	if m.SignalConfigs.MitigatingConfig.HeartbeatInterval.CurrentValue != nil {
		result += fmt.Sprintf("       \"%s\": %d\n", "current-value", *m.SignalConfigs.MitigatingConfig.HeartbeatInterval.CurrentValue)
	}
	result += fmt.Sprintf("     \"%s\":\n", "missing-hb-allowed")
	if m.SignalConfigs.MitigatingConfig.MissingHbAllowed.CurrentValue != nil {
		result += fmt.Sprintf("       \"%s\": %d\n", "current-value", *m.SignalConfigs.MitigatingConfig.MissingHbAllowed.CurrentValue)
	}
	result += fmt.Sprintf("     \"%s\":\n", "max-retransmit")
	if m.SignalConfigs.MitigatingConfig.MaxRetransmit.CurrentValue != nil {
		result += fmt.Sprintf("       \"%s\": %d\n", "current-value", *m.SignalConfigs.MitigatingConfig.MaxRetransmit.CurrentValue)
	}
	result += fmt.Sprintf("     \"%s\":\n", "ack-timeout")
	if m.SignalConfigs.MitigatingConfig.AckTimeout.CurrentValue != nil {
		current_float, _ = m.SignalConfigs.MitigatingConfig.AckTimeout.CurrentValue.Round(2).Float64()
		result += fmt.Sprintf("       \"%s\": %f\n", "current-value-decimal", current_float)
	}
	result += fmt.Sprintf("     \"%s\":\n", "ack-random-factor")
	if m.SignalConfigs.MitigatingConfig.AckRandomFactor.CurrentValue != nil {
		current_float, _ = m.SignalConfigs.MitigatingConfig.AckRandomFactor.CurrentValue.Round(2).Float64()
		result += fmt.Sprintf("       \"%s\": %f\n", "current-value-decimal", current_float)
	}

	result += fmt.Sprintf("   \"%s\":\n", "idle-config")
	result += fmt.Sprintf("     \"%s\":\n", "heartbeat-interval")
	if m.SignalConfigs.IdleConfig.HeartbeatInterval.CurrentValue != nil {
		result += fmt.Sprintf("       \"%s\": %d\n", "current-value", *m.SignalConfigs.IdleConfig.HeartbeatInterval.CurrentValue)
	}
	result += fmt.Sprintf("     \"%s\":\n", "missing-hb-allowed")
	if m.SignalConfigs.IdleConfig.MissingHbAllowed.CurrentValue != nil {
		result += fmt.Sprintf("       \"%s\": %d\n", "current-value", *m.SignalConfigs.IdleConfig.MissingHbAllowed.CurrentValue)
	}
	result += fmt.Sprintf("     \"%s\":\n", "max-retransmit")
	if m.SignalConfigs.IdleConfig.MaxRetransmit.CurrentValue != nil {
		result += fmt.Sprintf("       \"%s\": %d\n", "current-value", *m.SignalConfigs.IdleConfig.MaxRetransmit.CurrentValue)
	}
	result += fmt.Sprintf("     \"%s\":\n", "ack-timeout")
	if m.SignalConfigs.IdleConfig.AckTimeout.CurrentValue != nil {
		current_float, _ = m.SignalConfigs.IdleConfig.AckTimeout.CurrentValue.Round(2).Float64()
		result += fmt.Sprintf("       \"%s\": %f\n", "current-value-decimal", current_float)
	}
	result += fmt.Sprintf("     \"%s\":\n", "ack-random-factor")
	if m.SignalConfigs.IdleConfig.AckRandomFactor.CurrentValue != nil {
		current_float, _ = m.SignalConfigs.IdleConfig.AckRandomFactor.CurrentValue.Round(2).Float64()
		result += fmt.Sprintf("       \"%s\": %f\n", "current-value-decimal", current_float)
	}
	return
}

type HeartBeatRequest struct {
	_struct   bool      `codec:",uint"` //encode struct with "unsigned integer" keys
	HeartBeat HeartBeat `json:"ietf-dots-signal-channel:heartbeat" codec:"49,omitempty"`
}

type HeartBeat struct {
	_struct      bool  `codec:",uint"` //encode struct with "unsigned integer" keys
	PeerHbStatus *bool `json:"peer-hb-status" codec:"51,omitempty"`
}

/*
 * Convert SignalConfigRequest to strings
 */
func (hb *HeartBeatRequest) String() (result string) {
	result = "\n \"ietf-dots-signal-channel:heartbeat\":\n"
	if hb.HeartBeat.PeerHbStatus != nil {
		result += fmt.Sprintf("       \"%s\": %t\n", "peer-hb-status", *hb.HeartBeat.PeerHbStatus)
	}
	return
}

type TelemetrySetupRequest struct {
	_struct        bool           `codec:",uint"` //encode struct with "unsigned integer" keys
	TelemetrySetup TelemetrySetup `json:"ietf-dots-telemetry:telemetry-setup" codec:"32868,omitempty"`
}

type TelemetrySetup struct {
	_struct   bool        `codec:",uint"`                            //encode struct with "unsigned integer" keys
	Telemetry []Telemetry `json:"telemetry" codec:"32905,omitempty"` // CBOR key temp
}

type Telemetry struct {
	_struct                       bool                           `codec:",uint"` //encode struct with "unsigned integer" keys
	TelemetryConfigurationCurrent *TelemetryConfigurationCurrent `json:"current-config" codec:"32850,omitempty"`
	TotalPipeCapacity             []TotalPipeCapacity            `json:"total-pipe-capacity" codec:"32809,omitempty"`
	Baseline                      []Baseline                     `json:"baseline" codec:"32849,omitempty"`
}
type TelemetryConfigurationCurrent struct {
	_struct                   bool             `codec:",uint"`                                       //encode struct with "unsigned integer" keys
	MeasurementInterval       *int             `json:"measurement-interval" codec:"32857,omitempty"`
	MeasurementSample         *int             `json:"measurement-sample" codec:"32858,omitempty"`
	LowPercentile             *decimal.Decimal `json:"low-percentile" codec:"32803,omitempty"`
	MidPercentile             *decimal.Decimal `json:"mid-percentile" codec:"32804,omitempty"`
	HighPercentile            *decimal.Decimal `json:"high-percentile" codec:"32805,omitempty"`
	UnitConfigList            []UnitConfig     `json:"unit-config" codec:"32806,omitempty"`
	ServerOriginatedTelemetry *bool            `json:"server-originated-telemetry" codec:"32854,omitempty"`
	TelemetryNotifyInterval   *int             `json:"telemetry-notify-interval" codec:"32855,omitempty"`
}

type UnitConfig struct {
	_struct    bool  `codec:",uint"` //encode struct with "unsigned integer" keys
	Unit       *int  `json:"unit" codec:"32807,omitempty"`
	UnitStatus *bool `json:"unit-status" codec:"32808,omitempty"`
}

type TotalPipeCapacity struct {
	_struct  bool    `codec:",uint"`                           //encode struct with "unsigned integer" keys
	LinkId   *string `json:"link-id" codec:"32906,omitempty"`  // CBOR key temp
	Capacity *int    `json:"capacity" codec:"32907,omitempty"` // CBOR key temp
	Unit     *int    `json:"unit" codec:"32807,omitempty"`
}

type Baseline struct {
	_struct                    bool                      `codec:",uint"` //encode struct with "unsigned integer" keys
	Id                         *int                      `json:"id" codec:"32836,omitempty"`
	TargetPrefix               []string                  `json:"target-prefix" codec:"6,omitempty"`
	TargetPortRange            []PortRange               `json:"target-port-range" codec:"7,omitempty"`
	TargetProtocol             []int                     `json:"target-protocol" codec:"10,omitempty"`
	TargetFQDN                 []string                  `json:"target-fqdn" codec:"11,omitempty"`
	TargetURI                  []string                  `json:"target-uri" codec:"12,omitempty"`
	TotalTrafficNormalBaseline []Traffic                 `json:"total-traffic-normal-baseline" codec:"32812,omitempty"`
	TotalConnectionCapacity    []TotalConnectionCapacity `json:"total-connection-capacity" codec:"32819,omitempty"`
}

type Traffic struct {
	_struct         bool    `codec:",uint"` //encode struct with "unsigned integer" keys
	Unit            *int    `json:"unit" codec:"32807,omitempty"`
	Protocol        *uint8  `json:"protocol" codec:"10,omitempty"`
	LowPercentileG  *uint64 `json:"low-percentile-g" codec:"32813,omitempty"`
	MidPercentileG  *uint64 `json:"mid-percentile-g" codec:"32814,omitempty"`
	HighPercentileG *uint64 `json:"high-percentile-g" codec:"32815,omitempty"`
	PeakG           *uint64 `json:"peak-g" codec:"32816,omitempty"`
}
type TotalConnectionCapacity struct {
	_struct                bool    `codec:",uint"` //encode struct with "unsigned integer" keys
	Protocol               *uint8  `json:"protocol" codec:"10,omitempty"`
	Connection             *uint64 `json:"connection" codec:"32820,omitempty"`
	ConnectionClient       *uint64 `json:"connection-client" codec:"32821,omitempty"`
	Embryonic              *uint64 `json:"embryonic" codec:"32822,omitempty"`
	EmbryonicClient        *uint64 `json:"embryonic-client" codec:"32823,omitempty"`
	ConnectionPs           *uint64 `json:"connection-ps" codec:"32824,omitempty"`
	ConnectionClientPs     *uint64 `json:"connection-client-ps" codec:"32825,omitempty"`
	RequestPs              *uint64 `json:"request-ps" codec:"32826,omitempty"`
	RequestClientPs        *uint64 `json:"request-client-ps" codec:"32827,omitempty"`
	PartialRequestPs       *uint64 `json:"partial-request-ps" codec:"32828,omitempty"`
	PartialRequestClientPs *uint64 `json:"partial-request-client-ps" codec:"32829,omitempty"`
}

/*
 * Convert TelemetrySetupConfigurationRequest to strings
 */
func (ts *TelemetrySetupRequest) String() (result string) {
	result = "\n \"ietf-dots-telemetry:telemetry-setup\":\n"
	for key, t := range ts.TelemetrySetup.Telemetry {
		result += fmt.Sprintf("   \"%s[%d]\":\n", "telemetry", key+1)
		if t.TelemetryConfigurationCurrent != nil {
			result += "      \"current-config\":\n"
			tConfig := t.TelemetryConfigurationCurrent
			if tConfig.MeasurementInterval != nil {
				result += fmt.Sprintf("         \"%s\": %d\n", "measurement-interval", *tConfig.MeasurementInterval)
			}
			if tConfig.MeasurementSample != nil {
				result += fmt.Sprintf("         \"%s\": %d\n", "measurement-sample", *tConfig.MeasurementSample)
			}
			if tConfig.LowPercentile != nil {
				low, _ := tConfig.LowPercentile.Round(2).Float64()
				result += fmt.Sprintf("         \"%s\": %f\n", "low-percentile", low)
			}
			if tConfig.MidPercentile != nil {
				mid, _ := tConfig.MidPercentile.Round(2).Float64()
				result += fmt.Sprintf("         \"%s\": %f\n", "mid-percentile", mid)
			}
			if tConfig.HighPercentile != nil {
				high, _ := tConfig.HighPercentile.Round(2).Float64()
				result += fmt.Sprintf("         \"%s\": %f\n", "high-percentile", high)
			}
			for k, v := range tConfig.UnitConfigList {
				result += fmt.Sprintf("         \"%s[%d]\":\n", "unit-config", k+1)
				if v.Unit != nil {
					result += fmt.Sprintf("            \"%s\": %d\n", "unit", *v.Unit)
				}
				if v.UnitStatus != nil {
					result += fmt.Sprintf("            \"%s\": %t\n", "unit-status", *v.UnitStatus)
				}
			}
			if tConfig.ServerOriginatedTelemetry != nil {
				result += fmt.Sprintf("         \"%s\": %t\n", "server-initiated-telemetry", *tConfig.ServerOriginatedTelemetry)
			}
			if tConfig.TelemetryNotifyInterval != nil {
				result += fmt.Sprintf("         \"%s\": %d\n", "telemetry-notify-interval", *tConfig.TelemetryNotifyInterval)
			}
		}
		for k, v := range t.TotalPipeCapacity {
			result += fmt.Sprintf("      \"%s[%d]\":\n", "total-pipe-capacity", k+1)
			if v.LinkId != nil {
				result += fmt.Sprintf("         \"%s\": %s\n", "link-id", *v.LinkId)
			}
			if v.Capacity != nil {
				result += fmt.Sprintf("         \"%s\": %d\n", "capacity", *v.Capacity)
			}
			if v.Unit != nil {
				result += fmt.Sprintf("         \"%s\": %d\n", "unit", *v.Unit)
			}
		}
		for k, v := range t.Baseline {
			result += fmt.Sprintf("      \"%s[%d]\":\n", "baseline", k+1)
			if v.Id != nil {
				result += fmt.Sprintf("         \"%s\": %d\n", "id", *v.Id)
			}
			resultTargets := ConvertTargetsRequestToStrings(v.TargetPrefix, v.TargetPortRange, v.TargetProtocol, v.TargetFQDN, v.TargetURI)
			result += resultTargets
			for kNormalBaseline, vNormalBaseLine := range v.TotalTrafficNormalBaseline {
				result += fmt.Sprintf("         \"%s[%d]\":\n", "total-traffic-normal-baseline", kNormalBaseline+1)
				resultTotalTrafficNormalBaseLine := vNormalBaseLine.String()
				result += resultTotalTrafficNormalBaseLine

			}
			for kConnectionCapacity, vConnectionCapacity := range v.TotalConnectionCapacity {
				result += fmt.Sprintf("         \"%s[%d]\":\n", "total-connection-capacity", kConnectionCapacity+1)
				resultConnectionCapacity := vConnectionCapacity.String()
				result += resultConnectionCapacity
			}
		}

	}
	return
}

// Convert TagetsRequest to string
func ConvertTargetsRequestToStrings(prefixs []string, portRanges []PortRange, protocols []int, fqdns []string, uris []string) (result string) {
	for k, v := range prefixs {
		result += fmt.Sprintf("         \"%s[%d]\": %s\n", "target-prefix", k+1, v)
	}
	for k, v := range portRanges {
		result += fmt.Sprintf("         \"%s[%d]\":\n", "target-port-range", k+1)
		if v.LowerPort != nil {
			result += fmt.Sprintf("            \"%s\": %d\n", "lower-port", *v.LowerPort)
		}
		if v.UpperPort != nil {
			result += fmt.Sprintf("            \"%s\": %d\n", "upper-port", *v.UpperPort)
		}
	}
	for k, v := range protocols {
		result += fmt.Sprintf("         \"%s[%d]\": %d\n", "target-protocol", k+1, v)
	}
	for k, v := range fqdns {
		result += fmt.Sprintf("         \"%s[%d]\": %s\n", "target-fqdn", k+1, v)
	}
	for k, v := range uris {
		result += fmt.Sprintf("         \"%s[%d]\": %s\n", "target-uri", k+1, v)
	}
	return
}

// Convert Traffic to string
func (traffic Traffic) String() (result string) {
	if traffic.Unit != nil {
		result += fmt.Sprintf("            \"%s\": %d\n", "unit", *traffic.Unit)
	}
	if traffic.Protocol != nil {
		result += fmt.Sprintf("            \"%s\": %d\n", "protocol", *traffic.Protocol)
	}
	if traffic.LowPercentileG != nil {
		result += fmt.Sprintf("            \"%s\": %d\n", "low-percentile-g", *traffic.LowPercentileG)
	}
	if traffic.MidPercentileG != nil {
		result += fmt.Sprintf("            \"%s\": %d\n", "mid-percentile-g", *traffic.MidPercentileG)
	}
	if traffic.HighPercentileG != nil {
		result += fmt.Sprintf("            \"%s\": %d\n", "high-percentile-g", *traffic.HighPercentileG)
	}
	if traffic.PeakG != nil {
		result += fmt.Sprintf("            \"%s\": %d\n", "peak-g", *traffic.PeakG)
	}
	return
}

// Convert TotalConnectionCapacity to string
func (tcc TotalConnectionCapacity) String() (result string) {
	if tcc.Protocol != nil {
		result += fmt.Sprintf("            \"%s\": %d\n", "protocol", *tcc.Protocol)
	}
	if tcc.Connection != nil {
		result += fmt.Sprintf("            \"%s\": %d\n", "connection", *tcc.Connection)
	}
	if tcc.ConnectionClient != nil {
		result += fmt.Sprintf("            \"%s\": %d\n", "connection-client", *tcc.ConnectionClient)
	}
	if tcc.Embryonic != nil {
		result += fmt.Sprintf("            \"%s\": %d\n", "embryonic", *tcc.Embryonic)
	}
	if tcc.EmbryonicClient != nil {
		result += fmt.Sprintf("            \"%s\": %d\n", "embryonic-client", *tcc.EmbryonicClient)
	}
	if tcc.ConnectionPs != nil {
		result += fmt.Sprintf("            \"%s\": %d\n", "connection-ps", *tcc.ConnectionPs)
	}
	if tcc.ConnectionClientPs != nil {
		result += fmt.Sprintf("            \"%s\": %d\n", "connection-client-ps", *tcc.ConnectionClientPs)
	}
	if tcc.RequestPs != nil {
		result += fmt.Sprintf("            \"%s\": %d\n", "request-ps", *tcc.RequestPs)
	}
	if tcc.RequestClientPs != nil {
		result += fmt.Sprintf("            \"%s\": %d\n", "request-client-ps", *tcc.RequestClientPs)
	}
	if tcc.PartialRequestPs != nil {
		result += fmt.Sprintf("            \"%s\": %d\n", "partial-request-ps", *tcc.PartialRequestPs)
	}
	if tcc.PartialRequestClientPs != nil {
		result += fmt.Sprintf("            \"%s\": %d\n", "partial-request-client-ps", *tcc.PartialRequestClientPs)
	}
	return
}
